repos:
-   repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    -   id: black
        language_version: python3.12
        args:
          - --line-length=88
          - --target-version=py312
          - --include='\.pyi?$'

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.2
  hooks:
    - id: mypy
      name: mypy
      language_version: python3.12
      args:
        - --strict
        - --ignore-missing-imports
      additional_dependencies:
        - mypy==1.11.2
        - pytest==8.3.2
        - types-requests==2.31.0.0

-   repo: local
    hooks:
    -   id: update-version-and-verify
        name: Update version badges and verify changelog
        entry: python update_version_badge.py
        language: system
        always_run: true
        files: ^(README\.md|docs/index\.md|docs/CHANGELOG\.md|pyproject\.toml)$
        description: |
            Ensures that version badges in Markdown files are updated and
            the version exists in CHANGELOG.md. Fails if not consistent.
