# Mkdocs Configuration File

site_name: SharePyCrud Documentation
site_url: https://sharepycrud.readthedocs.io
theme:
  name: readthedocs


nav:
  - Home: index.md
  - Getting Started: setup.md
  - Changelog: CHANGELOG.md
  - Contributing: CONTRIBUTING.md
  - Architecture: ARCHITECTURE.md
  - Logging: LOGGING.md

# Add plugins
plugins:
  - search
