# Mkdocs Configuration File

site_name: SharePyCrud Documentation
site_url: https://sharepycrud.readthedocs.io
theme:
  name: readthedocs


nav:
  - Home: INDEX.md
  - Getting Started: SETUP.md
  - Changelog: CHANGELOG.md
  - Contributing: CONTRIBUTING.md
  - Coverage: coverage/index.html

# Add plugins
plugins:
  - search
