# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Python Tests and Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev,test]"
        pip install pytest-html
      if: always()

    - name: Install type stubs
      run: |
        pip install types-requests types-setuptools

    - name: Lint with Black
      run: |
        python -m black . --check

    - name: Type check with mypy
      run: |
        python -m mypy . --strict --ignore-missing-imports

    - name: Set environment variables
      env:
        SHAREPOINT_SITE: "test-site"
        CLIENT_ID: "dummy-client-id"
        CLIENT_SECRET: "dummy-secret"
        TENANT_ID: "dummy-tenant-id"
        SITE_NAME: "test-site-name"
        SHAREPOINT_URL: "https://example.sharepoint.com"
      run: echo "Environment variables set"

    - name: Test with pytest
      run: |
        mkdir -p test-results
        python -m pytest -s tests --junitxml=test-results/junit.xml --html=test-results/report.html --self-contained-html

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: ./test-results/
