# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Python Tests and Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip build
        pip install -e ".[dev,test]"
      if: always()

    - name: Lint with Black
      run: |
        python -m black . --check

    - name: Type check with mypy
      run: |
        python -m mypy . --strict --ignore-missing-imports

    - name: Set environment variables
      env:
        SHAREPOINT_SITE: "test-site"
        CLIENT_ID: "dummy-client-id"
        CLIENT_SECRET: "dummy-secret"
        TENANT_ID: "dummy-tenant-id"
        SITE_NAME: "test-site-name"
        SHAREPOINT_URL: "https://example.sharepoint.com"
      run: echo "Environment variables set"

    - name: Test with pytest and coverage
      run: |
        mkdir -p test-results coverage-results
        python -m pytest tests/ \
          --cov=src/sharepycrud \
          --cov-report=xml:coverage-results/coverage.xml \
          --cov-report=html:coverage-results/htmlcov \
          --junitxml=test-results/junit.xml \
          --html=test-results/report.html \
          --self-contained-html

    - name: Upload coverage results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-results
        path: ./coverage-results/
        if-no-files-found: error

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results
        path: ./test-results/
        if-no-files-found: error
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage-results/coverage.xml
        flags: unittests
        name: codecov-coverage-report
        fail_ci_if_error: true
